version: "3.9"

services:
  redis:
    container_name: ${PROJECT_PREFIX}_redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    env_file:
      - .env

  postgres:
    container_name: ${PROJECT_PREFIX}_postgres-db
    image: postgres:16.2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5

  backend:
    container_name: ${PROJECT_PREFIX}_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: django-backend:latest
    volumes:
      - ./backend:/app
      - static_data:/app/static
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    container_name: ${PROJECT_PREFIX}_celery-worker
    image: django-backend:latest
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
    env_file:
      - .env

  beat:
    container_name: ${PROJECT_PREFIX}_celery-beat
    image: django-backend:latest
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - backend
    volumes:
      - ./backend:/app
    env_file:
      - .env

  flower:
    container_name: ${PROJECT_PREFIX}_celery-flower
    image: mher/flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - backend
    env_file:
      - .env

  smtp4dev:
    container_name: ${PROJECT_PREFIX}_smtp4dev-mail
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "5001:80"
      - "2525:25"
      - "144:143"
    volumes:
      - smtp4dev-data:/smtp4dev
    env_file:
      - .env

volumes:
  postgres_data:
  smtp4dev-data:
  static_data:
  media_data: